### ISSUE TITLE
Cannot find module '@lhci/server/src/api/storage/storage-method.js'

### ISSUE THREAD

**Issue by trptcolin** [GoogleChrome/lighthouse-ci#247]
When running `lhci healthcheck` on the latest CLI version (`"@lhci/cli": "0.3.10"`), I get this error:

```
Cannot find module '@lhci/server/src/api/storage/storage-method.js'
Require stack:
- /PATH/REDACTED/node_modules/@lhci/cli/src/wizard/wizard.js
- /PATH/REDACTED/node_modules/@lhci/cli/src/cli.js
```

Things work fine in `"@lhci/cli": "0.3.9"`

I believe the issue is that #239 introduces a runtime dependency for `@lhci/cli` on the `@lhci/server` package, with no corresponding actual `package.json` dependency. [This line](https://github.com/GoogleChrome/lighthouse-ci/blob/34fc915c7ecb87776de2816a390c28be61b4f667/packages/cli/src/wizard/wizard.js#L10) specifically.

Workarounds that I can confirm are 👍 for me:
- Explicitly add `"@lhci/server": "0.3.10"` as a dependency.
- Downgrade to `"@lhci/cli": "0.3.9"`

I'm not sure whether the right fix is to explicitly add the server dependency, or to reconfigure things so it's not necessary, but wanted to at least file the workarounds for others who might hit this.

**Comment by patrickhulce** [comment]
Oof, thanks @trptcolin! We'll fix asap 👍

**Comment by NullVoxPopuli** [comment]
I have that, too: https://github.com/NullVoxPopuli/emberclear/pull/620/checks?check_run_id=519963353

**Comment by patrickhulce** [comment]
Published 0.3.11 that should fix this. Leaving this open while we figure out a test story that can test this situation better.

**Comment by trptcolin** [comment]
Wow that was quick. Thanks!

**Comment by Ethan-Arrowood** [comment]
Can confirm 0.3.11 fixed my ci! thank you :)
